### ISSUE TITLE
Extension won't work with AppDynamics Machine Agent version 20.3.2-2520

### ISSUE THREAD

**Issue by WeberTech** [Appdynamics/log-monitoring-extension#6]
I found a bug in the log extension 4.0.0.  When starting the machine agent, it fails to create the task for the extension.  This is what I found in the logs:

[Agent-Monitor-Scheduler-1] 17 Apr 2020 11:32:29,635 ERROR PeriodicTaskRunner - Error creating environment task 
java.lang.NoClassDefFoundError: org/apache/log4j/Layout
	at com.appdynamics.extensions.conf.modules.HealthCheckModule.initMATroubleshootChecks(HealthCheckModule.java:80) ~[?:?]
	at com.appdynamics.extensions.conf.MonitorContext.initialize(MonitorContext.java:93) ~[?:?]
	at com.appdynamics.extensions.conf.MonitorContextConfiguration.setConfigYml(MonitorContextConfiguration.java:80) ~[?:?]
	at com.appdynamics.extensions.ABaseMonitor$1.onFileChange(ABaseMonitor.java:132) ~[?:?]
	at com.appdynamics.extensions.conf.modules.FileWatchListenerModule.createListener(FileWatchListenerModule.java:52) ~[?:?]
	at com.appdynamics.extensions.conf.MonitorContextConfiguration.registerListener(MonitorContextConfiguration.java:146) ~[?:?]
	at com.appdynamics.extensions.ABaseMonitor.initialize(ABaseMonitor.java:122) ~[?:?]
	at com.appdynamics.extensions.ABaseMonitor.execute(ABaseMonitor.java:186) ~[?:?]
	at com.singularity.ee.agent.systemagent.components.monitormanager.managed.MonitorTaskRunner.runTask(MonitorTaskRunner.java:149) ~[machineagent.jar:Machine Agent v20.3.2-2520 GA compatible with 4.4.1.0 Build Date 2020-03-27 21:13:50]
	at com.singularity.ee.agent.systemagent.components.monitormanager.managed.PeriodicTaskRunner.runTask(PeriodicTaskRunner.java:86) ~[machineagent.jar:Machine Agent v20.3.2-2520 GA compatible with 4.4.1.0 Build Date 2020-03-27 21:13:50]
	at com.singularity.ee.agent.systemagent.components.monitormanager.managed.PeriodicTaskRunner.run(PeriodicTaskRunner.java:47) [machineagent.jar:Machine Agent v20.3.2-2520 GA compatible with 4.4.1.0 Build Date 2020-03-27 21:13:50]
	at com.singularity.ee.util.javaspecific.scheduler.AgentScheduledExecutorServiceImpl$SafeRunnable.run(AgentScheduledExecutorServiceImpl.java:122) [agent-4.5.13.2135.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_241]
	at com.singularity.ee.util.javaspecific.scheduler.ADFutureTask$Sync.innerRunAndReset(ADFutureTask.java:335) [agent-4.5.13.2135.jar:?]
	at com.singularity.ee.util.javaspecific.scheduler.ADFutureTask.runAndReset(ADFutureTask.java:152) [agent-4.5.13.2135.jar:?]
	at com.singularity.ee.util.javaspecific.scheduler.ADScheduledThreadPoolExecutor$ADScheduledFutureTask.access$101(ADScheduledThreadPoolExecutor.java:119) [agent-4.5.13.2135.jar:?]
	at com.singularity.ee.util.javaspecific.scheduler.ADScheduledThreadPoolExecutor$ADScheduledFutureTask.runPeriodic(ADScheduledThreadPoolExecutor.java:206) [agent-4.5.13.2135.jar:?]
	at com.singularity.ee.util.javaspecific.scheduler.ADScheduledThreadPoolExecutor$ADScheduledFutureTask.run(ADScheduledThreadPoolExecutor.java:236) [agent-4.5.13.2135.jar:?]
	at com.singularity.ee.util.javaspecific.scheduler.ADThreadPoolExecutor$Worker.runTask(ADThreadPoolExecutor.java:694) [agent-4.5.13.2135.jar:?]
	at com.singularity.ee.util.javaspecific.scheduler.ADThreadPoolExecutor$Worker.run(ADThreadPoolExecutor.java:726) [agent-4.5.13.2135.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Layout
	at com.singularity.ee.util.loader.FileSystemClassLoader.findClass(FileSystemClassLoader.java:372) ~[agent-4.5.13.2135.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241]
	at com.singularity.ee.util.loader.FileSystemClassLoader.loadClass(FileSystemClassLoader.java:320) ~[agent-4.5.13.2135.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
	... 21 more

**Comment by adityajagtiani89** [comment]
> I found a bug in the log extension 4.0.0. When starting the machine agent, it fails to create the task for the extension. This is what I found in the logs:
> 
> [Agent-Monitor-Scheduler-1] 17 Apr 2020 11:32:29,635 ERROR PeriodicTaskRunner - Error creating environment task
> java.lang.NoClassDefFoundError: org/apache/log4j/Layout
> at com.appdynamics.extensions.conf.modules.HealthCheckModule.initMATroubleshootChecks(HealthCheckModule.java:80) ~[?:?]
> at com.appdynamics.extensions.conf.MonitorContext.initialize(MonitorContext.java:93) ~[?:?]
> at com.appdynamics.extensions.conf.MonitorContextConfiguration.setConfigYml(MonitorContextConfiguration.java:80) ~[?:?]
> at com.appdynamics.extensions.ABaseMonitor$1.onFileChange(ABaseMonitor.java:132) ~[?:?]
> at com.appdynamics.extensions.conf.modules.FileWatchListenerModule.createListener(FileWatchListenerModule.java:52) ~[?:?]
> at com.appdynamics.extensions.conf.MonitorContextConfiguration.registerListener(MonitorContextConfiguration.java:146) ~[?:?]
> at com.appdynamics.extensions.ABaseMonitor.initialize(ABaseMonitor.java:122) ~[?:?]
> at com.appdynamics.extensions.ABaseMonitor.execute(ABaseMonitor.java:186) ~[?:?]
> at com.singularity.ee.agent.systemagent.components.monitormanager.managed.MonitorTaskRunner.runTask(MonitorTaskRunner.java:149) ~[machineagent.jar:Machine Agent v20.3.2-2520 GA compatible with 4.4.1.0 Build Date 2020-03-27 21:13:50]
> at com.singularity.ee.agent.systemagent.components.monitormanager.managed.PeriodicTaskRunner.runTask(PeriodicTaskRunner.java:86) ~[machineagent.jar:Machine Agent v20.3.2-2520 GA compatible with 4.4.1.0 Build Date 2020-03-27 21:13:50]
> at com.singularity.ee.agent.systemagent.components.monitormanager.managed.PeriodicTaskRunner.run(PeriodicTaskRunner.java:47) [machineagent.jar:Machine Agent v20.3.2-2520 GA compatible with 4.4.1.0 Build Date 2020-03-27 21:13:50]
> at com.singularity.ee.util.javaspecific.scheduler.AgentScheduledExecutorServiceImpl$SafeRunnable.run(AgentScheduledExecutorServiceImpl.java:122) [agent-4.5.13.2135.jar:?]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_241]
> at com.singularity.ee.util.javaspecific.scheduler.ADFutureTask$Sync.innerRunAndReset(ADFutureTask.java:335) [agent-4.5.13.2135.jar:?]
> at com.singularity.ee.util.javaspecific.scheduler.ADFutureTask.runAndReset(ADFutureTask.java:152) [agent-4.5.13.2135.jar:?]
> at com.singularity.ee.util.javaspecific.scheduler.ADScheduledThreadPoolExecutor$ADScheduledFutureTask.access$101(ADScheduledThreadPoolExecutor.java:119) [agent-4.5.13.2135.jar:?]
> at com.singularity.ee.util.javaspecific.scheduler.ADScheduledThreadPoolExecutor$ADScheduledFutureTask.runPeriodic(ADScheduledThreadPoolExecutor.java:206) [agent-4.5.13.2135.jar:?]
> at com.singularity.ee.util.javaspecific.scheduler.ADScheduledThreadPoolExecutor$ADScheduledFutureTask.run(ADScheduledThreadPoolExecutor.java:236) [agent-4.5.13.2135.jar:?]
> at com.singularity.ee.util.javaspecific.scheduler.ADThreadPoolExecutor$Worker.runTask(ADThreadPoolExecutor.java:694) [agent-4.5.13.2135.jar:?]
> at com.singularity.ee.util.javaspecific.scheduler.ADThreadPoolExecutor$Worker.run(ADThreadPoolExecutor.java:726) [agent-4.5.13.2135.jar:?]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
> Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Layout
> at com.singularity.ee.util.loader.FileSystemClassLoader.findClass(FileSystemClassLoader.java:372) ~[agent-4.5.13.2135.jar:?]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241]
> at com.singularity.ee.util.loader.FileSystemClassLoader.loadClass(FileSystemClassLoader.java:320) ~[agent-4.5.13.2135.jar:?]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
> ... 21 more

Hello, this is a known issue and affects a number of extensions due to a log4j dependency conflict. We are starting work on fixing these issues and will let you know once this has been completed. Thanks!

**Comment by shahidmgr** [comment]
Hi Team,

Please use 4.0.1 this issue is fixed.

Thanks,
Shahid
